# Generated by Django 4.1.7 on 2023-02-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarLoan',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('ext_routing_payment', models.CharField(max_length=150)),
                ('ext_acct_num_payment', models.CharField(max_length=150)),
                ('loan_Size', models.BigIntegerField()),
                ('apr', models.IntegerField()),
                ('monthly_payment', models.CharField(max_length=150)),
                ('payment_due', models.CharField(max_length=150)),
                ('routing_num', models.IntegerField()),
                ('account_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompoundInvesting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Compound_interest_Percent', models.CharField(max_length=255)),
                ('invest_num', models.CharField(max_length=255)),
                ('routing_num', models.IntegerField()),
                ('account_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseLoad',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('ext_routing_payment', models.CharField(max_length=150)),
                ('ext_acct_num_payment', models.CharField(max_length=150)),
                ('loan_Size', models.BigIntegerField()),
                ('apr', models.IntegerField()),
                ('monthly_payment', models.CharField(max_length=150)),
                ('payment_due', models.CharField(max_length=150)),
                ('routing_num', models.IntegerField()),
                ('account_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('ext_routing_payment', models.CharField(max_length=150)),
                ('ext_acct_num_payment', models.CharField(max_length=150)),
                ('loan_Size', models.BigIntegerField()),
                ('apr', models.IntegerField()),
                ('monthly_payment', models.CharField(max_length=150)),
                ('payment_due', models.CharField(max_length=150)),
                ('routing_num', models.IntegerField()),
                ('account_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MainAccount',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('checking', models.CharField(max_length=150)),
                ('saving', models.CharField(max_length=150)),
                ('routing_num', models.IntegerField()),
                ('account_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('routing_num', models.IntegerField()),
                ('account_num', models.IntegerField()),
            ],
        ),
    ]
